"=============================================================================
" vimrc
"-----------------------------------------------------------------------------

" This file bootstraps our vim configuration. This file has three goals:
" - Preconfigure core vim paths for lookups and temp files.
" - Load all pathogen plugins and their related help info.
" - Load the 'real' vim configuration found in ~/.vimrc.after.
" Using an 'after' file via autocmd lets us override plugin settings. NOTE
" however that we have to define certain settings before load or the plugin in
" question may not initialize correctly.

" Make sure our local ~/.vim directory is part of the runtime search path.
set runtimepath+=~/.vim

" Put any working files (.swp etc) in ~/temporary.
set backupdir=~/temporary
set directory=~/temporary

" Map , to command prefix. Do this before loading plugins to ensure they pick up
" the proper leader setting for any keymappings they may do. (seems some
" mappings end up on \ if we don't do this early).
let mapleader=","

" The airline plugin reads this early and so we can't set it after the plugin
" has loaded if we want it to take effect.
let g:airline#extensions#default#section_truncate_width = {}
set laststatus=2
set ttimeoutlen=50

" Default to 4 space indents (TIBET style). Filetype mappings and editorconfig
" should override when they have explicit mappings.
set expandtab list tabstop=4 softtabstop=4 shiftwidth=4

" Activate pathogen to load any installed plugins. Plugins are found in the
" ~/.vim/bundle directory.
execute pathogen#infect()
syntax on
filetype plugin indent on

" Generate help for the loaded plugins.
execute pathogen#helptags()

" Redirect remaining work into an 'after' file by using an autocmd so we come in
" after any pathogen plugins are loaded. This lets us override settings more
" consistently. Note that things like the color scheme or anything triggered by
" the after file itself will still load last and could override things so it's
" better to keep that file's content to primarily set/map and not autocmd etc.
augroup idearat
  au VimEnter * so ~/.vimrc.after

  " For some reason this has to be last or vim-airline doesn't init properly.
  " It'll start, but the font-based icons won't display until insert/split.
  " Setting laststatus=2 per the airline docs doesn't seem to affect this.
  colorscheme idearat
augroup end

"=============================================================================
