#!/bin/bash
#
# .tibetrc: This file is triggered by .login.after.
#
# This file runs after ALL shell logic so it's got override power. Use wisely :)

# ---
# aliases
# ---

alias base='export TIBET_HOME="${TPI_HOME}/TIBET"'
alias base3='export TIBET_HOME="${TPI_HOME}/TIBET3"'

alias 3='base3;cdtibet;clear'
alias 5='base;cdtibet;clear'

# work from old codebase for now
base

# bash environment management
alias vimtibet="vi $HOME/.tibetrc"
alias srctibet="source $HOME/.tibetrc"

alias forms='cd ${DEVL_HOME}/WebSanity/formsanity-ng;clear'

alias cdsite='cd ${TPI_HOME}/technicalpursuit.com'
alias site='base;cdsite;clear'
alias cdtpi='cd ${TPI_HOME}'
alias tpi='base;cdtpi;clear'
alias cdwiki='cd ${TPI_HOME}/TIBET.wiki'
alias wiki='base;cdwiki;clear'
alias cdpages='cd ${TPI_HOME}/TechnicalPursuit.github.io'
alias pages='base;cdpages;clear'

alias cddbsa='cd ${DEVL_HOME}/DBSA'
alias cdtibet='cd ${TIBET_HOME}'

alias d2d='cd ~/tmp/d2d'
alias tdc='cd ${TIBET_HOME}/src/tibet/tools/tdc'
alias tds='cd ${TIBET_HOME}/etc/tds/'
alias sherpa='cd ${TIBET_HOME}/src/tibet/tools/sherpa'

alias cli='5;cd src/tibet/cli;clear'
alias dna='5;cd dna;clear'

alias tpcfg='cd ${TIBET_HOME}/lib/cfg'
alias tplib='cd ${TIBET_HOME}/lib'
alias tpsrc='cd ${TIBET_HOME}/src'
alias tptst='cd ${TIBET_HOME}/test'

alias chsh='cd ${TIBET_HOME}/chsh'

alias tpboot='5;cd src/tibet/boot'
alias tpdist='5;cd build'

alias tptdk='cd ${TIBET_HOME}/src/tibet'

alias tpcss='cd ${TIBET_HOME}/lib/styles'
alias tpdat='cd ${TIBET_HOME}/lib/dat'
alias tphtml='cd ${TIBET_HOME}/lib/html'
alias tpxsl='cd ${TIBET_HOME}/lib/xsl'

alias tpkernel='cd ${TIBET_HOME}/src/tibet/kernel'
alias tpshell='cd ${TIBET_HOME}/src/tibet/shells'
alias tpstorage='cd ${TIBET_HOME}/src/tibet/storage'
alias tptesting='cd ${TIBET_HOME}/src/tibet/testing'

alias tpacl='cd ${TIBET_HOME}/src/acl'
alias tpamz='cd ${TIBET_HOME}/src/amz'
alias tpev='cd ${TIBET_HOME}/src/ev'
alias tpgoog='cd ${TIBET_HOME}/src/goog'
alias tpsig='cd ${TIBET_HOME}/src/sig'
alias tpsmil='cd ${TIBET_HOME}/src/smil'
alias tpsvg='cd ${TIBET_HOME}/src/svg'
alias tptibet='cd ${TIBET_HOME}/src/tibet'
alias tptsh='cd ${TIBET_HOME}/src/tsh'
alias tpxctrls='cd ${TIBET_HOME}/src/xctrls'
alias tpxhtml='cd ${TIBET_HOME}/src/xhtml'
alias tpxml='cd ${TIBET_HOME}/src/xml'
alias tpxmpp='cd ${TIBET_HOME}/src/xmpp'
alias tpxs='cd ${TIBET_HOME}/src/xs'

# ---
# eof
# ---

