#!/bin/bash
#
# .tibetrc: This file is triggered by .login.after.
#
# This file runs after ALL shell logic so it's got override power. Use wisely :)


# ---
# exports
# ---

export FIRSTCLASS_HOME="${PROJECT_HOME}/FirstClass"
export TPI_HOME="${DEVL_HOME}/TPI"
export TIBET_HOME="${TPI_HOME}/TIBET"

# ---
# aliases
# ---

alias cdfb='cd ${PROJECT_HOME}/fiscalball'
alias cdfc='cd ${FIRSTCLASS_HOME}'
alias cdtab='cd ${PROJECT_HOME}/tabmarks'
alias cdviz='cd ${PROJECT_HOME}/vizitd'

alias bedney='export TIBET_HOME="${TPI_HOME}/Bedney/TIBET"'
alias 3='bedney;cdtibet;clear'

alias base='export TIBET_HOME="${TPI_HOME}/TIBET"'
alias 5='base;cdtibet;clear'

# work from old codebase for now
base

# bash environment management
alias vimtibet="vi $HOME/.tibetrc"
alias srctibet="source $HOME/.tibetrc"

# cd directory aliases
alias cdbedney='cd ${TPI_HOME}/Bedney/TIBET'
alias cdtibet='cd ${TIBET_HOME}'
alias cdnotes="cd ${TPI_HOME}/notes"
alias cdtsh='cd ${TIBET_HOME}/tsh'

alias cdtdp='cd ${TIBET_HOME}/tdp'
alias cdsherpa='cd ${TIBET_HOME}/sherpa'

alias cdtpi='cd ${TPI_HOME}'
alias cddbsa='cd ${DEVL_HOME}/DBSA'
alias cdsite='cd ${TPI_HOME}/sites/technicalpursuit.com'
alias cdwiki='cd ${TPI_HOME}/sites/TIBET.wiki'

alias site='cd ${TPI_HOME}/sites/technicalpursuit.com'
alias wiki='cd ${TPI_HOME}/sites/TIBET.wiki'

alias tpcfg='cd ${TIBET_HOME}/base/cfg'
alias tpdat='cd ${TIBET_HOME}/base/dat'
alias tpdemo='cd ${TIBET_HOME}/base/doc/demo'
alias tpdoc='cd ${TIBET_HOME}/base/doc'
alias tpetc='cd ${TIBET_HOME}/base/etc'
alias tplib='cd ${TIBET_HOME}/base/lib'
alias tpsrc='cd ${TIBET_HOME}/base/src'
alias tptst='cd ${TIBET_HOME}/base/tst'

alias chsh='cd ${TIBET_HOME}/chsh'

alias tns='cd ${TIBET_HOME}/base/src'
alias tsh='cd ${TIBET_HOME}/base/src/tsh'

#alias tpboot='cd ${TIBET_HOME}/sherpa/TIBET-INF/base/lib/tibet/src'
#alias tpboot='cd ${TPI_HOME}/Bedney/TIBET/sherpa/TIBET-INF/base/lib/tibet/src'
#alias tpboot='cd ${TPI_HOME}/Bedney/TIBET/tdp/TIBET-INF/base/lib/tibet/src'
alias tpboot='cd ${TPI_HOME}/Bedney/TIBET/base/lib/tibet/src'

alias tptdk='cd ${TIBET_HOME}/base/src/tibet'

alias tpcss='cd ${TIBET_HOME}/base/lib/tibet/css'
alias tphtml='cd ${TIBET_HOME}/base/lib/tibet/html'
alias tpxsl='cd ${TIBET_HOME}/base/lib/tibet/html'

alias tpeffects='cd ${TIBET_HOME}/base/src/tibet/effects'
alias tpkernel='cd ${TIBET_HOME}/base/src/tibet/kernel'
alias tpserv='cd ${TIBET_HOME}/base/src/tibet/services'
alias tpshell='cd ${TIBET_HOME}/base/src/tibet/shells'
alias tpsnip='cd ${TIBET_HOME}/base/doc/snippets'
alias tpstorage='cd ${TIBET_HOME}/base/src/tibet/storage'

alias tpacl='cd ${TIBET_HOME}/base/src/acl'
alias tpamz='cd ${TIBET_HOME}/base/src/amz'
alias tpbpel='cd ${TIBET_HOME}/base/src/bpel'
alias tpcssml='cd ${TIBET_HOME}/base/src/css'
alias tpdnd='cd ${TIBET_HOME}/base/src/dnd'
alias tpev='cd ${TIBET_HOME}/base/src/ev'
alias tpgoog='cd ${TIBET_HOME}/base/src/goog'
alias tpsig='cd ${TIBET_HOME}/base/src/sig'
alias tpsmil='cd ${TIBET_HOME}/base/src/smil'
alias tpsvg='cd ${TIBET_HOME}/base/src/svg'
alias tptibet='cd ${TIBET_HOME}/base/src/tibet'
alias tptsh='cd ${TIBET_HOME}/base/src/tsh'
alias tpxctrls='cd ${TIBET_HOME}/base/src/xctrls'
alias tpxhtml='cd ${TIBET_HOME}/base/src/xhtml'
alias tpxml='cd ${TIBET_HOME}/base/src/xml'
alias tpxmpp='cd ${TIBET_HOME}/base/src/xmpp'
alias tpxs='cd ${TIBET_HOME}/base/src/xs'
alias tpyui='cd ${TIBET_HOME}/base/src/yui'

# ---
# eof
# ---
