#!/bin/bash
#
# .tibetrc: This file is triggered by .login.after.
#
# This file runs after ALL shell logic so it's got override power. Use wisely :)

# ---
# aliases
# ---

alias base='export TIBET_HOME="${CODERATS_HOME}/TIBET"'
alias base3='export TIBET_HOME="${TPI_HOME}/GITHUB/TIBET3"'
alias base5='export TIBET_HOME="${TPI_HOME}/TIBET"'

alias 0='base;cdtibet;clear'
alias 3='base3;cdtibet;clear'
alias 5='base5;cdtibet;clear'

# work from old codebase for now
base

alias coderats='cd ${CODERATS_HOME}/coderats-llc'
alias getsherpa='cd ${CODERATS_HOME}/getsherpa-app'
alias sherpa='cd ${CODERATS_HOME}/sherpa'
alias cf='cd ${CODERATS_HOME}/command-flow'
alias cdtibet='cd ${TIBET_HOME};clear'

# bash environment management
alias vimtibet="vi $HOME/.tibetrc"
alias srctibet="source $HOME/.tibetrc"

alias forms='cd ${DEVL_HOME}/WebSanity/formsanity;clear'

alias cdsite='cd ${TPI_HOME}/technicalpursuit-com'
alias site='cdsite;clear'
alias sitedoc='cdsite;cd doc/sources;clear'
alias tpi='cdtpi;clear'
alias cdwiki='cd ${TPI_HOME}/TIBET.wiki'
alias wiki='cdwiki;clear'
alias cdpages='cd ${TPI_HOME}/GITHUB/TechnicalPursuit.github.io'
alias pages='cdpages;clear'
alias examples='cd ${TPI_HOME}/TIBET-Examples'
alias pizza='examples; cd pizza'

alias cddbsa='cd ${DEVL_HOME}/DBSA'
alias cdtpi='cd ${TPI_HOME}'
alias cdrats='cd ${CODERATS_HOME}'

alias dbtest='cd ~/temporary/dbtest'
alias d2d='cd ~/temporary/d2d'
alias hello='cd ~/temporary/hello'
alias elect='cd ~/temporary/electron'
alias t2='cd ~/temporary/t2'
alias todo='cd ~/temporary/todomvc'
alias tws='tibet tws'

alias tdc='cd ${TIBET_HOME}/src/tibet/tools/tdc'
alias tds='cd ${TIBET_HOME}/tds/'
alias lama='cd ${TIBET_HOME}/src/tibet/tools/lama'
alias lamadev='cd ${TIBET_HOME}/src/tibet/tools/tibet-lama-extension'

alias cli='cd ${TIBET_HOME}/src/tibet/cli;clear'
alias dna='cd ${TIBET_HOME}/dna;clear'

alias tpcfg='cd ${TIBET_HOME}/lib/cfg'
alias tpcmd='cd ${TIBET_HOME}/cmd/make'
alias tpdoc='cd ${TIBET_HOME}/doc/markdown'
alias tpetc='cd ${TIBET_HOME}/etc/'
alias tplib='cd ${TIBET_HOME}/lib'
alias tpsrc='cd ${TIBET_HOME}/src'
alias tptst='cd ${TIBET_HOME}/test'
alias tptest='cd ${TIBET_HOME}/test'

alias chsh='cd ${TIBET_HOME}/chsh'

alias tpboot='cd ${TIBET_HOME}/src/tibet/boot'
alias tpdist='cd ${TIBET_HOME}/build'

alias tptdk='cd ${TIBET_HOME}/src/tibet'

alias tpcss='cd ${TIBET_HOME}/lib/styles'
alias tpdat='cd ${TIBET_HOME}/lib/dat'
alias tphtml='cd ${TIBET_HOME}/lib/html'
alias tpxsl='cd ${TIBET_HOME}/lib/xsl'

alias tpkernel='cd ${TIBET_HOME}/src/tibet/kernel'
alias tpshell='cd ${TIBET_HOME}/src/tibet/shells'
alias tpstorage='cd ${TIBET_HOME}/src/tibet/storage'
alias tptesting='cd ${TIBET_HOME}/src/tibet/testing'

alias tpacl='cd ${TIBET_HOME}/src/acl'
alias tpamz='cd ${TIBET_HOME}/src/amz'
alias tpev='cd ${TIBET_HOME}/src/ev'
alias tpgoog='cd ${TIBET_HOME}/src/goog'
alias tpsig='cd ${TIBET_HOME}/src/sig'
alias tpsmil='cd ${TIBET_HOME}/src/smil'
alias tpsvg='cd ${TIBET_HOME}/src/svg'
alias tptibet='cd ${TIBET_HOME}/src/tibet'
alias tptsh='cd ${TIBET_HOME}/src/tsh'
alias tpxctrls='cd ${TIBET_HOME}/src/xctrls'
alias tpxhtml='cd ${TIBET_HOME}/src/xhtml'
alias tpxml='cd ${TIBET_HOME}/src/xml'
alias tpxmpp='cd ${TIBET_HOME}/src/xmpp'
alias tpxs='cd ${TIBET_HOME}/src/xs'

alias xctrls='cd ${TIBET_HOME}/src/xctrls'

# ---
# tibet
# ---

which tibet > /dev/null && . "$( tibet --initpath )"

# ---
# eof
# ---

