#!/bin/bash
[[ -s /Users/ss/.local.before ]] && source /Users/ss/.local.before
[[ -s /Users/ss/.localrc ]] && source /Users/ss/.localrc
[[ -s /Users/ss/.local.after ]] && source /Users/ss/.local.after
