#!/bin/bash
#
# .bash_profile: runs for LOGIN shells only.

[[ -s ${HOME}/.login.before ]] && source ${HOME}/.login.before
[[ -s ${HOME}/.bashrc ]] && source ${HOME}/.bashrc
[[ -s ${HOME}/.login.after ]] && source ${HOME}/.login.after

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh # This loads NVM
